### ISSUE TITLE
Move to ipfs/ipfs-shipyard?

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/ipfs-multipart#2]
Hello @fbaiodias!

Would it be OK to move this repository to either under the IPFS or the IPFS-Shipyard organization on GitHub?

This would be useful for automatic inclusion in our CI system + easier for people to contribute and to find the project.

**Comment by diasdavid** [comment]
ping @fbaiodias

**Comment by fbaiodias** [comment]
Sure, just tell me which org you want and I'll transfer it :)

**Comment by diasdavid** [comment]
`ipfs` Thanks!

**Comment by fbaiodias** [comment]
Done 😃

**Comment by diasdavid** [comment]
Based on https://github.com/ipfs/pm/issues/600, would you like to assume the role of Lead Maintainer or do you prefer to pass the baton?

**Comment by fbaiodias** [comment]
@diasdavid I would prefer to pass the baton if there's anyone interested.
